# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'kgn'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Review', folder: 'pages', file: 'review.html'}
- {name: 'Game', folder: 'pages', file: 'game.html'}
- {name: "Novel", folder: "pages", file: "novel.html"}
- {name: "Animation", folder: "pages", file: "animation.html"}
# - {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
# - {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
# - {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
# - {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
# - {name: 'About', folder: 'pages', file: 'about.html'}
# - {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'facebook', link: 'https://www.facebook.com/100015843072119'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'envelope', link: 'kwh3884858@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
